/**
 * Mock data for development and testing
 * This file contains mock teams and players data
 */

import type { Player } from '../models/Player';
import type { Team } from '../models/Team';

// Team name mapping for quick lookup
export const teamNames: Record<string, string> = {
  '1': 'New York Yankees',
  '2': 'Los Angeles Dodgers',
  '3': 'Houston Astros',
  '4': 'Atlanta Braves',
  '5': 'Tampa Bay Rays',
  '6': 'San Francisco Giants',
  '7': 'Toronto Blue Jays',
  '8': 'Chicago White Sox',
};

// Mock team data with complete statistics
export const mockTeams: Pick<Team, 'id' | 'name' | 'abbreviation' | 'statistics'>[] = [
  {
    id: '1',
    name: 'New York Yankees',
    abbreviation: 'NYY',
    statistics: {
      season: 2024,
      wins: 95,
      losses: 67,
      winPercentage: 0.586,
      gamesBack: 0,
      runsScored: 815,
      runsAllowed: 678,
      runDifferential: 137,
      teamBattingAverage: 0.268,
      teamOnBasePercentage: 0.342,
      teamSluggingPercentage: 0.456,
      teamHomeRuns: 245,
      teamStolenBases: 112,
      teamERA: 3.72,
      teamWHIP: 1.23,
      teamStrikeouts: 1456,
      teamSaves: 52,
      fieldingPercentage: 0.986,
      errors: 78,
      doublePlays: 142,
    },
  },
  {
    id: '2',
    name: 'Los Angeles Dodgers',
    abbreviation: 'LAD',
    statistics: {
      season: 2024,
      wins: 98,
      losses: 64,
      winPercentage: 0.605,
      gamesBack: 0,
      runsScored: 842,
      runsAllowed: 645,
      runDifferential: 197,
      teamBattingAverage: 0.272,
      teamOnBasePercentage: 0.349,
      teamSluggingPercentage: 0.468,
      teamHomeRuns: 258,
      teamStolenBases: 134,
      teamERA: 3.54,
      teamWHIP: 1.19,
      teamStrikeouts: 1523,
      teamSaves: 58,
      fieldingPercentage: 0.988,
      errors: 68,
      doublePlays: 155,
    },
  },
  {
    id: '3',
    name: 'Houston Astros',
    abbreviation: 'HOU',
    statistics: {
      season: 2024,
      wins: 90,
      losses: 72,
      winPercentage: 0.556,
      gamesBack: 8,
      runsScored: 789,
      runsAllowed: 712,
      runDifferential: 77,
      teamBattingAverage: 0.264,
      teamOnBasePercentage: 0.335,
      teamSluggingPercentage: 0.442,
      teamHomeRuns: 218,
      teamStolenBases: 95,
      teamERA: 3.92,
      teamWHIP: 1.28,
      teamStrikeouts: 1398,
      teamSaves: 48,
      fieldingPercentage: 0.984,
      errors: 89,
      doublePlays: 138,
    },
  },
  {
    id: '4',
    name: 'Atlanta Braves',
    abbreviation: 'ATL',
    statistics: {
      season: 2024,
      wins: 92,
      losses: 70,
      winPercentage: 0.568,
      gamesBack: 0,
      runsScored: 823,
      runsAllowed: 695,
      runDifferential: 128,
      teamBattingAverage: 0.269,
      teamOnBasePercentage: 0.343,
      teamSluggingPercentage: 0.461,
      teamHomeRuns: 242,
      teamStolenBases: 156,
      teamERA: 3.81,
      teamWHIP: 1.25,
      teamStrikeouts: 1434,
      teamSaves: 54,
      fieldingPercentage: 0.985,
      errors: 82,
      doublePlays: 147,
    },
  },
  {
    id: '5',
    name: 'Tampa Bay Rays',
    abbreviation: 'TB',
    statistics: {
      season: 2024,
      wins: 88,
      losses: 74,
      winPercentage: 0.543,
      gamesBack: 10,
      runsScored: 758,
      runsAllowed: 721,
      runDifferential: 37,
      teamBattingAverage: 0.256,
      teamOnBasePercentage: 0.328,
      teamSluggingPercentage: 0.425,
      teamHomeRuns: 195,
      teamStolenBases: 118,
      teamERA: 3.98,
      teamWHIP: 1.31,
      teamStrikeouts: 1367,
      teamSaves: 46,
      fieldingPercentage: 0.983,
      errors: 92,
      doublePlays: 132,
    },
  },
  {
    id: '6',
    name: 'San Francisco Giants',
    abbreviation: 'SF',
    statistics: {
      season: 2024,
      wins: 85,
      losses: 77,
      winPercentage: 0.525,
      gamesBack: 13,
      runsScored: 741,
      runsAllowed: 734,
      runDifferential: 7,
      teamBattingAverage: 0.258,
      teamOnBasePercentage: 0.331,
      teamSluggingPercentage: 0.432,
      teamHomeRuns: 202,
      teamStolenBases: 88,
      teamERA: 4.05,
      teamWHIP: 1.33,
      teamStrikeouts: 1345,
      teamSaves: 44,
      fieldingPercentage: 0.982,
      errors: 96,
      doublePlays: 128,
    },
  },
  {
    id: '7',
    name: 'Toronto Blue Jays',
    abbreviation: 'TOR',
    statistics: {
      season: 2024,
      wins: 87,
      losses: 75,
      winPercentage: 0.537,
      gamesBack: 11,
      runsScored: 772,
      runsAllowed: 745,
      runDifferential: 27,
      teamBattingAverage: 0.261,
      teamOnBasePercentage: 0.334,
      teamSluggingPercentage: 0.438,
      teamHomeRuns: 215,
      teamStolenBases: 102,
      teamERA: 4.11,
      teamWHIP: 1.35,
      teamStrikeouts: 1312,
      teamSaves: 42,
      fieldingPercentage: 0.981,
      errors: 101,
      doublePlays: 125,
    },
  },
  {
    id: '8',
    name: 'Chicago White Sox',
    abbreviation: 'CWS',
    statistics: {
      season: 2024,
      wins: 72,
      losses: 90,
      winPercentage: 0.444,
      gamesBack: 26,
      runsScored: 682,
      runsAllowed: 798,
      runDifferential: -116,
      teamBattingAverage: 0.245,
      teamOnBasePercentage: 0.312,
      teamSluggingPercentage: 0.398,
      teamHomeRuns: 168,
      teamStolenBases: 76,
      teamERA: 4.42,
      teamWHIP: 1.42,
      teamStrikeouts: 1245,
      teamSaves: 38,
      fieldingPercentage: 0.978,
      errors: 115,
      doublePlays: 118,
    },
  },
];

// Mock player data for display
export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'Aaron Judge',
    number: 99,
    position: 'RF',
    teamId: '1',
    dateOfBirth: '1992-04-26',
    height: '6\'7"',
    weight: 282,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 148,
      atBats: 550,
      runs: 120,
      hits: 177,
      doubles: 28,
      triples: 1,
      homeRuns: 58,
      rbi: 144,
      walks: 111,
      strikeouts: 175,
      stolenBases: 16,
      caughtStealing: 3,
      hitByPitch: 12,
      sacrificeFlies: 8,
      battingAverage: 0.322,
      onBasePercentage: 0.458,
      sluggingPercentage: 0.686,
      ops: 1.144,
    },
  },
  {
    id: '2',
    name: 'Shohei Ohtani',
    number: 17,
    position: 'P',
    teamId: '2',
    dateOfBirth: '1994-07-05',
    height: '6\'4"',
    weight: 210,
    bats: 'L',
    throws: 'R',
    statistics: {
      gamesPlayed: 157,
      atBats: 599,
      runs: 134,
      hits: 184,
      doubles: 38,
      triples: 7,
      homeRuns: 54,
      rbi: 130,
      walks: 81,
      strikeouts: 133,
      stolenBases: 59,
      caughtStealing: 9,
      hitByPitch: 11,
      sacrificeFlies: 7,
      battingAverage: 0.307,
      onBasePercentage: 0.39,
      sluggingPercentage: 0.654,
      ops: 1.044,
      wins: 15,
      losses: 9,
      saves: 0,
      inningsPitched: 132.0,
      hitsAllowed: 107,
      runsAllowed: 58,
      earnedRuns: 53,
      walksAllowed: 44,
      strikeoutsRecorded: 167,
      era: 3.61,
      whip: 1.14,
    },
  },
  {
    id: '3',
    name: 'Mookie Betts',
    number: 50,
    position: 'RF',
    teamId: '2',
    dateOfBirth: '1992-10-07',
    height: '5\'9"',
    weight: 180,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 142,
      atBats: 520,
      runs: 122,
      hits: 163,
      doubles: 35,
      triples: 5,
      homeRuns: 35,
      rbi: 107,
      walks: 82,
      strikeouts: 88,
      stolenBases: 16,
      caughtStealing: 4,
      hitByPitch: 9,
      sacrificeFlies: 6,
      battingAverage: 0.313,
      onBasePercentage: 0.408,
      sluggingPercentage: 0.579,
      ops: 0.987,
    },
  },
  {
    id: '4',
    name: 'Jose Altuve',
    number: 27,
    position: '2B',
    teamId: '3',
    dateOfBirth: '1990-05-06',
    height: '5\'6"',
    weight: 166,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 158,
      atBats: 640,
      runs: 95,
      hits: 194,
      doubles: 41,
      triples: 3,
      homeRuns: 15,
      rbi: 69,
      walks: 42,
      strikeouts: 82,
      stolenBases: 18,
      caughtStealing: 5,
      hitByPitch: 5,
      sacrificeFlies: 4,
      battingAverage: 0.303,
      onBasePercentage: 0.353,
      sluggingPercentage: 0.446,
      ops: 0.799,
    },
  },
  {
    id: '5',
    name: 'Ronald Acuña Jr.',
    number: 13,
    position: 'RF',
    teamId: '4',
    dateOfBirth: '1997-12-18',
    height: '6\'0"',
    weight: 205,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 155,
      atBats: 590,
      runs: 149,
      hits: 185,
      doubles: 32,
      triples: 9,
      homeRuns: 41,
      rbi: 106,
      walks: 75,
      strikeouts: 155,
      stolenBases: 73,
      caughtStealing: 11,
      hitByPitch: 14,
      sacrificeFlies: 7,
      battingAverage: 0.337,
      onBasePercentage: 0.416,
      sluggingPercentage: 0.596,
      ops: 1.012,
    },
  },
  {
    id: '6',
    name: 'Freddie Freeman',
    number: 5,
    position: '1B',
    teamId: '2',
    dateOfBirth: '1989-09-12',
    height: '6\'5"',
    weight: 220,
    bats: 'L',
    throws: 'R',
    statistics: {
      gamesPlayed: 147,
      atBats: 550,
      runs: 102,
      hits: 174,
      doubles: 39,
      triples: 4,
      homeRuns: 29,
      rbi: 102,
      walks: 74,
      strikeouts: 84,
      stolenBases: 13,
      caughtStealing: 2,
      hitByPitch: 8,
      sacrificeFlies: 5,
      battingAverage: 0.331,
      onBasePercentage: 0.41,
      sluggingPercentage: 0.567,
      ops: 0.977,
    },
  },
  {
    id: '7',
    name: 'Randy Arozarena',
    number: 56,
    position: 'LF',
    teamId: '5',
    dateOfBirth: '1995-02-28',
    height: '5\'11"',
    weight: 185,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 152,
      atBats: 578,
      runs: 92,
      hits: 149,
      doubles: 30,
      triples: 3,
      homeRuns: 23,
      rbi: 89,
      walks: 52,
      strikeouts: 125,
      stolenBases: 37,
      caughtStealing: 8,
      hitByPitch: 7,
      sacrificeFlies: 4,
      battingAverage: 0.258,
      onBasePercentage: 0.325,
      sluggingPercentage: 0.434,
      ops: 0.759,
    },
  },
  {
    id: '8',
    name: 'Brandon Crawford',
    number: 35,
    position: 'SS',
    teamId: '6',
    dateOfBirth: '1987-01-21',
    height: '6\'2"',
    weight: 223,
    bats: 'L',
    throws: 'R',
    statistics: {
      gamesPlayed: 119,
      atBats: 392,
      runs: 42,
      hits: 91,
      doubles: 20,
      triples: 1,
      homeRuns: 11,
      rbi: 48,
      walks: 35,
      strikeouts: 82,
      stolenBases: 2,
      caughtStealing: 1,
      hitByPitch: 3,
      sacrificeFlies: 2,
      battingAverage: 0.232,
      onBasePercentage: 0.298,
      sluggingPercentage: 0.368,
      ops: 0.666,
    },
  },
  {
    id: '9',
    name: 'Vladimir Guerrero Jr.',
    number: 27,
    position: '1B',
    teamId: '7',
    dateOfBirth: '1999-03-16',
    height: '6\'2"',
    weight: 250,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 159,
      atBats: 617,
      runs: 90,
      hits: 179,
      doubles: 44,
      triples: 1,
      homeRuns: 26,
      rbi: 94,
      walks: 79,
      strikeouts: 99,
      stolenBases: 2,
      caughtStealing: 1,
      hitByPitch: 6,
      sacrificeFlies: 5,
      battingAverage: 0.29,
      onBasePercentage: 0.377,
      sluggingPercentage: 0.477,
      ops: 0.854,
    },
  },
  {
    id: '10',
    name: 'Tim Anderson',
    number: 7,
    position: 'SS',
    teamId: '8',
    dateOfBirth: '1993-06-23',
    height: '6\'1"',
    weight: 185,
    bats: 'R',
    throws: 'R',
    statistics: {
      gamesPlayed: 135,
      atBats: 532,
      runs: 62,
      hits: 142,
      doubles: 23,
      triples: 2,
      homeRuns: 6,
      rbi: 25,
      walks: 19,
      strikeouts: 107,
      stolenBases: 13,
      caughtStealing: 6,
      hitByPitch: 4,
      sacrificeFlies: 1,
      battingAverage: 0.267,
      onBasePercentage: 0.297,
      sluggingPercentage: 0.349,
      ops: 0.646,
    },
  },
];
