/**
 * Mock data for development and testing
 * This file contains mock teams and players data
 */

import type { Player } from '../models/Player';
import type { Team } from '../models/Team';

// Team name mapping for quick lookup
export const teamNames: Record<string, string> = {
  '1': 'New York Yankees',
  '2': 'Los Angeles Dodgers',
  '3': 'Houston Astros',
  '4': 'Atlanta Braves',
  '5': 'Tampa Bay Rays',
  '6': 'San Francisco Giants',
  '7': 'Toronto Blue Jays',
  '8': 'Chicago White Sox',
};

// Mock team data for display
export const mockTeams: Pick<Team, 'id' | 'name' | 'abbreviation' | 'statistics'>[] = [
  {
    id: '1',
    name: 'New York Yankees',
    abbreviation: 'NYY',
    statistics: { season: 2024, wins: 95, losses: 67, winPercentage: 0.586 } as Team['statistics'],
  },
  {
    id: '2',
    name: 'Los Angeles Dodgers',
    abbreviation: 'LAD',
    statistics: { season: 2024, wins: 98, losses: 64, winPercentage: 0.605 } as Team['statistics'],
  },
  {
    id: '3',
    name: 'Houston Astros',
    abbreviation: 'HOU',
    statistics: { season: 2024, wins: 90, losses: 72, winPercentage: 0.556 } as Team['statistics'],
  },
  {
    id: '4',
    name: 'Atlanta Braves',
    abbreviation: 'ATL',
    statistics: { season: 2024, wins: 92, losses: 70, winPercentage: 0.568 } as Team['statistics'],
  },
  {
    id: '5',
    name: 'Tampa Bay Rays',
    abbreviation: 'TB',
    statistics: { season: 2024, wins: 88, losses: 74, winPercentage: 0.543 } as Team['statistics'],
  },
  {
    id: '6',
    name: 'San Francisco Giants',
    abbreviation: 'SF',
    statistics: { season: 2024, wins: 85, losses: 77, winPercentage: 0.525 } as Team['statistics'],
  },
  {
    id: '7',
    name: 'Toronto Blue Jays',
    abbreviation: 'TOR',
    statistics: { season: 2024, wins: 87, losses: 75, winPercentage: 0.537 } as Team['statistics'],
  },
  {
    id: '8',
    name: 'Chicago White Sox',
    abbreviation: 'CWS',
    statistics: { season: 2024, wins: 72, losses: 90, winPercentage: 0.444 } as Team['statistics'],
  },
];

// Mock player data for display
export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'Aaron Judge',
    number: 99,
    position: 'RF',
    teamId: '1',
    dateOfBirth: '1992-04-26',
    height: '6\'7"',
    weight: 282,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '2',
    name: 'Shohei Ohtani',
    number: 17,
    position: 'P',
    teamId: '2',
    dateOfBirth: '1994-07-05',
    height: '6\'4"',
    weight: 210,
    bats: 'L',
    throws: 'R',
  },
  {
    id: '3',
    name: 'Mookie Betts',
    number: 50,
    position: 'RF',
    teamId: '2',
    dateOfBirth: '1992-10-07',
    height: '5\'9"',
    weight: 180,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '4',
    name: 'Jose Altuve',
    number: 27,
    position: '2B',
    teamId: '3',
    dateOfBirth: '1990-05-06',
    height: '5\'6"',
    weight: 166,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '5',
    name: 'Ronald Acuña Jr.',
    number: 13,
    position: 'RF',
    teamId: '4',
    dateOfBirth: '1997-12-18',
    height: '6\'0"',
    weight: 205,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '6',
    name: 'Freddie Freeman',
    number: 5,
    position: '1B',
    teamId: '2',
    dateOfBirth: '1989-09-12',
    height: '6\'5"',
    weight: 220,
    bats: 'L',
    throws: 'R',
  },
  {
    id: '7',
    name: 'Randy Arozarena',
    number: 56,
    position: 'LF',
    teamId: '5',
    dateOfBirth: '1995-02-28',
    height: '5\'11"',
    weight: 185,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '8',
    name: 'Brandon Crawford',
    number: 35,
    position: 'SS',
    teamId: '6',
    dateOfBirth: '1987-01-21',
    height: '6\'2"',
    weight: 223,
    bats: 'L',
    throws: 'R',
  },
  {
    id: '9',
    name: 'Vladimir Guerrero Jr.',
    number: 27,
    position: '1B',
    teamId: '7',
    dateOfBirth: '1999-03-16',
    height: '6\'2"',
    weight: 250,
    bats: 'R',
    throws: 'R',
  },
  {
    id: '10',
    name: 'Tim Anderson',
    number: 7,
    position: 'SS',
    teamId: '8',
    dateOfBirth: '1993-06-23',
    height: '6\'1"',
    weight: 185,
    bats: 'R',
    throws: 'R',
  },
];
